[package]
name = "flarate"
version = "0.1.0"
authors = ["kang"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 2

[dependencies]
lazy_static = "1.4.0"
regex = "1"
getset = "0.1.*"
num-traits = "0.2"
